steps:
  # --- STEP 1: META-VALIDATION (The Guardian) ---
  # This step validates the build configuration itself before proceeding.
  - name: 'python:3.11-slim'
    id: 'Validate Build Configuration'
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install google-generativeai pathlib && \
        python3 scripts/validate_cloudbuild.py
    # This secret should be configured in your GCP project's Secret Manager.
    secretEnv: ['GEMINI_API_KEY']

  # --- STEP 2: BUILD THE DOCKER IMAGE ---
  # This step only runs if the Guardian step above passes.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Application Image'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/stealth-seekers/app-backend:latest', '.']
    waitFor: ['Validate Build Configuration']

  # --- STEP 3: PUSH THE DOCKER IMAGE ---
  # Pushes the newly built image to Google Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image to Artifact Registry'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/stealth-seekers/app-backend:latest']
    waitFor: ['Build Application Image']

  # --- STEP 4: DEPLOY TO CLOUD RUN ---
  # Deploys the container image to your Cloud Run service.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'stealth-seekers-backend' # <-- Your Cloud Run service name
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/stealth-seekers/app-backend:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated' # Or configure as needed
    waitFor: ['Push Image to Artifact Registry']

# Define the location where your built images will be stored.
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/stealth-seekers/app-backend:latest'

# Link the environment variable to the secret stored in Secret Manager.
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/gemini-api-key/versions/latest
    env: AIzaSyDgeffdQcSceB56jm4MJjaqHTgN1PxzPNs
