# This is the Cloud Build configuration file for our CI (Continuous Integration) pipeline.
# It defines the steps to lint, test, build, and push our Docker image.

steps:
  # Step 1: Install Python dependencies
  # We install both app dependencies from requirements.txt and dev tools like black, flake8, and pytest.
  - name: 'python:3.11-slim'
    id: 'Install Dependencies'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m venv /workspace/venv
        . /workspace/venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 pytest # <--- ADDED: Install dev tools

  # Step 2: Lint with Black
  # This step will now find the 'black' command because it was installed in the previous step.
  - name: 'python:3.11-slim'
    id: 'Lint with Black'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        . /workspace/venv/bin/activate
        black . --check

  # Step 3: Lint with Flake8
  - name: 'python:3.11-slim'
    id: 'Lint with Flake8'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        . /workspace/venv/bin/activate
        flake8 .

  # Step 4: Run Unit & Integration Tests with Pytest
  - name: 'python:3.11-slim'
    id: 'Run Tests'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        . /workspace/venv/bin/activate
        pytest

  # Step 5: Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${_GCP_PROJECT}/${_ARTIFACT_REPO}/flux-api:$SHORT_SHA'
      - '.'

  # Step 6: Push the Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args:
      - 'push'
      - '${_GCP_REGION}-docker.pkg.dev/${_GCP_PROJECT}/${_ARTIFACT_REPO}/flux-api:$SHORT_SHA'

# This specifies the final image that was built and pushed.
images:
  - '${_GCP_REGION}-docker.pkg.dev/${_GCP_PROJECT}/${_ARTIFACT_REPO}/flux-api:$SHORT_SHA'

# Increase the default timeout to 15 minutes.
timeout: '900s'

# Define build-wide options.
options:
  logging: CLOUD_LOGGING_ONLY
